################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctions.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q7.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q31.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f16.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f32.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f64.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q15.c \
../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctions.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q7.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q31.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f16.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f32.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f64.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q15.o \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q31.o 

C_DEPS += \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctions.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q7.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q31.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f16.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f32.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f64.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q15.d \
./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/%.o Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/%.su Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/%.cyclo: ../Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/%.c Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F446xx -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/nekonotsuki/STM32CubeIDE/workspace_1.19.0/FreeRTOS/Projet_RTOS/Core/user_Lib/MYLIBRARY/inc" -I"/home/nekonotsuki/STM32CubeIDE/workspace_1.19.0/FreeRTOS/Projet_RTOS/Core/user_Lib/NekoNoLib/inc" -I"/home/nekonotsuki/STM32CubeIDE/workspace_1.19.0/FreeRTOS/Projet_RTOS/Core/user_Lib/CMSIS_DSP/Include" -I"/home/nekonotsuki/STM32CubeIDE/workspace_1.19.0/FreeRTOS/Projet_RTOS/Core/user_Lib/CMSIS_DSP/PrivateInclude" -I"/home/nekonotsuki/STM32CubeIDE/workspace_1.19.0/FreeRTOS/Projet_RTOS/Core/user_Lib/CMSIS_DSP/ComputeLibrary/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Core-2f-user_Lib-2f-CMSIS_DSP-2f-Source-2f-StatisticsFunctions

clean-Core-2f-user_Lib-2f-CMSIS_DSP-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctions.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctions.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctions.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctions.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmax_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o
	-$(RM) ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_absmin_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_entropy_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d
	-$(RM) ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_max_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mean_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo
	-$(RM) ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_min_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_mse_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q7.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q7.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q7.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_power_q7.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q31.o
	-$(RM) ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_rms_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_std_q31.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f16.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f16.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f16.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f16.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f32.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f32.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f32.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f32.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f64.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f64.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f64.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_f64.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q15.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q15.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q15.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q15.su ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q31.cyclo ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q31.d ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q31.o ./Core/user_Lib/CMSIS_DSP/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-Core-2f-user_Lib-2f-CMSIS_DSP-2f-Source-2f-StatisticsFunctions

